

package watermarking;

import java.io.File;
import javax.swing.JOptionPane;


public class embedmsg extends javax.swing.JFrame {

    private File f1;
    private File f2;

    /** Creates new form embedmsg */
    public embedmsg(File f1, File f2) {
        this.f1 = f1;
        this.f2 = f2;
        initComponents();
    }

    private embedmsg() {
        initComponents();
    }
   
   
   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        msgarea = new javax.swing.JScrollPane();
        msgfield = new javax.swing.JTextArea();
        msglabel = new javax.swing.JLabel();
        msgnext = new javax.swing.JButton();
        msgback = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("write message");
        getContentPane().setLayout(null);

        msgfield.setColumns(20);
        msgfield.setRows(5);
        msgarea.setViewportView(msgfield);

        getContentPane().add(msgarea);
        msgarea.setBounds(30, 40, 330, 160);

        msglabel.setText("Message");
        getContentPane().add(msglabel);
        msglabel.setBounds(40, 10, 100, 14);

        msgnext.setText("Next");
        msgnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgnextActionPerformed(evt);
            }
        });
        getContentPane().add(msgnext);
        msgnext.setBounds(150, 240, 90, 23);

        msgback.setText("Back");
        msgback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgbackActionPerformed(evt);
            }
        });
        getContentPane().add(msgback);
        msgback.setBounds(280, 240, 90, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-408)/2, (screenSize.height-334)/2, 408, 334);
    }// </editor-fold>//GEN-END:initComponents

    private void msgnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgnextActionPerformed
        if (msgfield.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "enter message");
        } else {
            new password(f1, f2, msgfield.getText(), null).setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_msgnextActionPerformed

    private void msgbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgbackActionPerformed
        this.setVisible(false);
         new base().setVisible(true);
    }//GEN-LAST:event_msgbackActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new embedmsg().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane msgarea;
    private javax.swing.JButton msgback;
    private javax.swing.JTextArea msgfield;
    private javax.swing.JLabel msglabel;
    private javax.swing.JButton msgnext;
    // End of variables declaration//GEN-END:variables
    
}
