/*
 * NewJFrame.java
 *
 * Created on July 10, 2008, 7:41 PM
 */

package watermarking;

/**
 *
 * @author  valakannikal
 */
public class Home extends javax.swing.JFrame {
    
    /** Creates new form NewJFrame */
    public Home() {
       
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        digital = new javax.swing.JLabel();
        watermarking = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        aboutus = new javax.swing.JLabel();
        help = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setForeground(new java.awt.Color(255, 255, 255));

        digital.setFont(new java.awt.Font("Impact", 1, 48));
        digital.setForeground(new java.awt.Color(51, 51, 255));
        digital.setText("DIGITAL");

        watermarking.setFont(new java.awt.Font("Impact", 1, 48));
        watermarking.setForeground(new java.awt.Color(51, 51, 255));
        watermarking.setText("WATERMARKING");

        go.setBackground(new java.awt.Color(51, 153, 0));
        go.setFont(new java.awt.Font("Tahoma", 3, 12));
        go.setText("go");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(204, 51, 0));
        exit.setFont(new java.awt.Font("Tahoma", 3, 12));
        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        aboutus.setFont(new java.awt.Font("Tahoma", 1, 18));
        aboutus.setForeground(new java.awt.Color(51, 51, 255));
        aboutus.setText("About us");
        aboutus.setEnabled(false);
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutusMouseExited(evt);
            }
        });

        help.setBackground(new java.awt.Color(204, 204, 255));
        help.setFont(new java.awt.Font("Tahoma", 1, 18));
        help.setForeground(new java.awt.Color(51, 51, 255));
        help.setText("Help");
        help.setEnabled(false);
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(go)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutus)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(digital)
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(watermarking, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboutus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(help))
                .addGap(68, 68, 68)
                .addComponent(digital, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(watermarking, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(go)
                    .addComponent(exit))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-453)/2, (screenSize.height-370)/2, 453, 370);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
   String message=
            "\nSoftware development team :\n" +
                    "          KAVITHA RAMACHANDRAN\n"+
                    "          ARUN KUMAR V\n" +
                    "          VANDANA T V\n"+
                    "          PRAVEEN P\n"+
                    "Copyright@KavithaArunVandanaPraveen2008.All rights reserved.\n " +
                    "This is our projectwork,under the guidance of Mr.VIJUSHANKAR\n"+
                    "We would like to add an information that this software program is\n"+
                    "protected by copyright law.Therefore unauthorized reproduction or\n" +
                    "distribution of this program,or a portion of it without license\n" +
                    "may result in severe crime penalities and will be prosecuted to\n"+
                    "the maximum extent possible under the law...\n"+
                    "'We had a goal in our mind and we worked hard to come up with this,so\n"+
                    "Do not be frightened. Awake, be up and doing. Do not stop until\n"+
                    "you have reached the goal.'\n"+
                    
                
                  "                                   *********************";
               
   
   new Details(message);
        
}//GEN-LAST:event_aboutusMouseClicked

    private void aboutusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseEntered
      aboutus.setEnabled(true);  // TODO add your handling code here:
}//GEN-LAST:event_aboutusMouseEntered

    private void aboutusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseExited
       aboutus.setEnabled(false);
}//GEN-LAST:event_aboutusMouseExited

    private void helpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseEntered
help.setEnabled(true);        // TODO add your handling code here:
}//GEN-LAST:event_helpMouseEntered

    private void helpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseExited
help.setEnabled(false);        // TODO add your handling code here:
}//GEN-LAST:event_helpMouseExited

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
String message="HELLO FRIENDS......\n"+
     "Digital watermarking is a technique used for secure data transfer\n"+
     "and for copy right protection.This program will hides information\n"+
     "by utilizing the unused density of images.\n"+
     "SOFTWARE REQUIREMENTS:\n"+
     "OS:WINDOWS/ME/2000/XP\n"+
     "JAVA\n"+
     "HARDWARE REQUIREMENTS:\n"+
     "Pentium IV processor,RAM 512Mb,80Gb harddisc,Standard keyboard and \n" +
     "a standard mouse\n"+
     
     "STEPS:\n"+
     "How to embed information?\n" +
     "!choose embed option and select an image file and a copy of it is used to\n"+
     "embed information and choose the information type that means you can embed\n"+
     "just a text message inside the image or any kind of file of compatible size\n"+
     "around 15Mb sized files can be embeded inside a standard image.And you can\n" +
     "set password and compression values." +
     "\n\nHow to retrieve information inside?\n"+
     "select the retrieve option from main frame and choose the embeded file you \n" +
     "received from the network or the one you stored for safety and then retrieve\n" +
     "the hidden file or message.\n"+
     "Once embeded you cannot add another information on that copy,however since \n" +
     "we are working with the copy.you can update your details in the original \n" +
     "image incase of copyright protection.last but not the least,we wont claim that\n " +
     "ours is a complete perfect project,since nothing can " +
     "be perfect " +
     "and perfection,\n" +
     "we would call it a journey rather than a destination so there may be \n"+
     "always scope for developments and improvements\n"+
     "with that note,we proudly present this work before you,lets do it....";
    
     
     
new Details(message);// TODO add your handling code here:
}//GEN-LAST:event_helpMouseClicked

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
this.setVisible(false);
new select().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_goActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    dispose();        
    }//GEN-LAST:event_exitActionPerformed
    
   
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutus;
    private javax.swing.JLabel digital;
    private javax.swing.JButton exit;
    public javax.swing.JButton go;
    private javax.swing.JLabel help;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel watermarking;
    // End of variables declaration//GEN-END:variables
    
}
