

package watermarking;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class retrieve extends javax.swing.JFrame {
    private File f1;
    
    /** Creates new form retrieve */
    public retrieve() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        retfield = new javax.swing.JTextField();
        retbrowse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        retnext = new javax.swing.JButton();
        retback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("retrieve");
        getContentPane().setLayout(null);
        getContentPane().add(retfield);
        retfield.setBounds(100, 130, 150, 20);

        retbrowse.setText("Browse");
        retbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retbrowseActionPerformed(evt);
            }
        });
        getContentPane().add(retbrowse);
        retbrowse.setBounds(280, 130, 90, 23);

        jLabel1.setText("SELECT THE FILE TO RETRIEVE ?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 100, 190, 14);

        retnext.setText("Next");
        retnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retnextActionPerformed(evt);
            }
        });
        getContentPane().add(retnext);
        retnext.setBounds(190, 230, 80, 23);

        retback.setText("Back");
        retback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retbackActionPerformed(evt);
            }
        });
        getContentPane().add(retback);
        retback.setBounds(290, 230, 80, 23);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-408)/2, (screenSize.height-334)/2, 408, 334);
    }// </editor-fold>//GEN-END:initComponents

    private void retbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retbrowseActionPerformed
          
 
        JFileChooser fc = new JFileChooser();
      
        fc.addChoosableFileFilter(new imgfilter());
         fc.setAccessory(new FilePreviewer(fc));     
       
        int result = fc.showDialog(null, "SELECT IMAGE");

        if (result == JFileChooser.APPROVE_OPTION) {
            f1 = fc.getSelectedFile();
          if ((f1.getName().toLowerCase().endsWith(".jpg") ||
                f1.getName().toLowerCase().endsWith(".jpeg")||
                f1.getName().toLowerCase().endsWith(".bmp") ||
                f1.getName().toLowerCase().endsWith(".gif") ||
                f1.getName().toLowerCase().endsWith(".png")||
                f1.getName().toLowerCase().endsWith(".tif")) == false)
            JOptionPane.showMessageDialog(null, "Please select an image file"
               , "information!",JOptionPane.INFORMATION_MESSAGE);
        else   
            if(f1.exists()==false)
                JOptionPane.showMessageDialog(this,"File not found\n" +
                        "Verify whether correct filename was given");
            else
                retfield.setText(f1.getName());
        }
        else if (result == JFileChooser.CANCEL_OPTION)             
            fc.setVisible(false);
       
    }//GEN-LAST:event_retbrowseActionPerformed

    private void retnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retnextActionPerformed
 
         if (retfield.getText().length() < 1) 
            JOptionPane.showMessageDialog(this, "please select any file");
         else
         {
       SteganoInformation steg=new SteganoInformation(f1,this);
     
     new info(steg).setVisible(true);
     setVisible(false);
}//GEN-LAST:event_retnextActionPerformed
    }
         private void retbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retbackActionPerformed
             // TODO add your handling code here:
             this.setVisible(false);
             new select().setVisible(true);
         }//GEN-LAST:event_retbackActionPerformed
        
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new retrieve().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton retback;
    private javax.swing.JButton retbrowse;
    private javax.swing.JTextField retfield;
    private javax.swing.JButton retnext;
    // End of variables declaration//GEN-END:variables
    
}
