
package watermarking;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class selectfile extends javax.swing.JFrame {

    File f1;
    File f2;
    File f3;

    /** Creates new form selectfile */
    public selectfile(File f1, File f2) {
        this.f1 = f1;
        this.f2 = f2;
        initComponents();
    }

    private selectfile() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filelabel = new javax.swing.JLabel();
        filefield = new javax.swing.JTextField();
        filebrowse = new javax.swing.JButton();
        filenext = new javax.swing.JButton();
        fileback = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("select file");
        getContentPane().setLayout(null);

        filelabel.setText("select input  file");
        getContentPane().add(filelabel);
        filelabel.setBounds(10, 70, 90, 14);
        getContentPane().add(filefield);
        filefield.setBounds(120, 70, 150, 20);

        filebrowse.setText("browse");
        filebrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filebrowseActionPerformed(evt);
            }
        });
        getContentPane().add(filebrowse);
        filebrowse.setBounds(280, 70, 90, 23);

        filenext.setText("Next");
        filenext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filenextActionPerformed(evt);
            }
        });
        getContentPane().add(filenext);
        filenext.setBounds(140, 230, 100, 20);

        fileback.setText("Back");
        fileback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filebackActionPerformed(evt);
            }
        });
        getContentPane().add(fileback);
        fileback.setBounds(273, 230, 100, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-402)/2, (screenSize.height-334)/2, 402, 334);
    }// </editor-fold>//GEN-END:initComponents

    private void filebrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filebrowseActionPerformed
      JFileChooser fc=new JFileChooser();
        fc.addChoosableFileFilter(new imgfilter());
        
        fc.setAccessory(new FilePreviewer(fc));
        
    
        int result = fc.showDialog(null, "SELECT FILE");

        if (result == JFileChooser.APPROVE_OPTION) {
            f3 = fc.getSelectedFile();
             if(f3.exists()==false)
                JOptionPane.showMessageDialog(this,"File not found\nVerify whether correct filename was given");
            else
                filefield.setText(f3.getName());
            
        } else if (result == JFileChooser.CANCEL_OPTION) 
            fc.setVisible(false);
        

       
    }//GEN-LAST:event_filebrowseActionPerformed

    private void filenextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filenextActionPerformed
        if (filefield.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "select any file");
        } else {
            new password(f1, f2, null, f3).setVisible(true);
            setVisible(false);
           


        }
    }//GEN-LAST:event_filenextActionPerformed

    private void filebackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filebackActionPerformed
        this.setVisible(false);
         new base().setVisible(true);
    }//GEN-LAST:event_filebackActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new selectfile().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileback;
    private javax.swing.JButton filebrowse;
    private javax.swing.JTextField filefield;
    private javax.swing.JLabel filelabel;
    private javax.swing.JButton filenext;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
